### ISSUE TITLE
Blood salvo sometimes cancelling.

### ISSUE THREAD

**Issue by Rufert** [Rim-Of-Madness-Team/Rim-of-Madness---Vampires#6]
Have had this happen with a few other targeted ranged abilities too, but blood salvo seems to be the one that does it most reliably. 

What I've noticed:
Casting seems to cancel in the last 10% of the casting timer. Blood is spent and the ability goes on cooldown.
It doesn't seem to matter if the casting pawn is in cover.
It does not seem to matter if the target is in cover.

**Comment by SamboyCoding** [comment]
Can't repro this one - need more info. Does this still happen in a fresh world with only JecsTools and Vamps, and can you attach the output_log.txt file, found in the Rimworld_Data folder, once you do get it to happen. 

I tested this with the latest build of the mod, on a fresh world, only jecstools and vamps, and the projectiles launched as expected, flew to their targets, contacted them, removing 2 blood with a "-2" above their heads, flew back to the caster, and 2 "+2" labels appeared, and the vitae level increased by 4.

**Comment by SamboyCoding** [comment]
Also, if it doesn't happen without other mods, see if you can find what mod causes it. Or alternatively post your mod list and I'll try and take a look, but this will obviously take longer to fix.
